spring:
  cloud:
    alicloud:
        oss:
          bucket: glj-mall
    nacos:
      discovery:
        server-addr: 192.168.2.112:8848
  application:
    name: mall-third-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 30000

